#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Console\MakeControllerCommand;
use App\Console\MakeModelCommand;
use App\Console\MakeRouteCommand;

$app = new Application('MeuFramework CLI', '0.1');

$app->add(new MakeControllerCommand());
$app->add(new MakeModelCommand());
$app->add(new MakeRouteCommand());

$app->run();