#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Console\MakeControllerCommand;
use App\Console\MakeModelCommand;
use App\Console\MakeRouteCommand;
use App\Console\MakeMiddlewareCommand;

$app = new Application('FWPHP CLI', '0.1');

$app->add(new MakeControllerCommand());
$app->add(new MakeModelCommand());
$app->add(new MakeRouteCommand());
$app->add(new MakeMiddlewareCommand());

$app->run();